server:
  port: 8100
eureka:  client:    service-url:      defaultzone: http://localhost:8761/eureka
      
resilience4j:
  bulkhead:    instances:      default:
        max-concurrent-calls: 10
  ratelimiter:    instances:      default:
        limit-for-period: 2
        limit-refresh-period: 10s  retry:    instances:      default:
        max-attempts: 3
      foo:
        max-attempts: 6
        wait-duration: 1s
        enable-exponential-backoff: true

spring:  application:    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password:  
